### PR TITLE
Client for Falco Version API

### LINKED ISSUE #34: Support the new Falco version API
**Motivation**

Falco is soon providing a new gRPC endpoint to let clients obtains its version (also, in parts: major, minor, patch, prerelease, build).

The PR containing this feature is https://github.com/falcosecurity/falco/pull/872.

**Feature**

Write a client and examples for it.

### PR DESCRIPTION
**Pull request by leodido**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area api

/area client

/area examples

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #34

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
new: version API client
```

### CODE REVIEW

**Comment by leodido** [comment]
/hold

until https://github.com/falcosecurity/falco/pull/872 is merged into Falco.

Also the proto's path needs to be updated.

**Review by fntlnz — DISMISSED** [review]

**Review by fntlnz — APPROVED** [review]

**Pull request merged**
