### PR TITLE
Update OWNERS to include rajibmitra

### LINKED ISSUE #6: Volunteer as owner for client go.
Hi Team, 

I would like to volunteer as owner of our client go repository, I have some experience writing go with unit test cases. I would love get involved building this go client. 

Thanks,

### PR DESCRIPTION
**Pull request by rajibmitra**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #6

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by leodido — COMMENTED** [review]
Thanks for proposing yourself!
Could you please fill (kind, etc.) the PR template in order for this PR to have everything in place to get merged in? Thanks :)

**Comment by fntlnz** [comment]
I did the needed changes to the pr description however I cannot sign off the commits for you @rajibmitra - once you do that we will be able to approve and merge this.

Please read [here for the policy](https://github.com/falcosecurity/falco/blob/dev/CONTRIBUTING.md#developer-certificate-of-origin) and [here for the git command line parameter](https://github.com/git/git/blob/b2c150d3aa82f6583b9aadfecc5f8fa1c74aca09/Documentation/git-commit.txt#L154-L161)

**Comment by leodido** [comment]
Hey @rajibmitra  to sign the commit look here in the [contribution guidelines](https://github.com/falcosecurity/falco/blob/dev/CONTRIBUTING.md#developer-certificate-of-origin).

**Comment by rajibmitra** [comment]
This is my commit message

Signed-off-by: John Poiana <jpoiana@falco.org>

**Comment by rajibmitra** [comment]
Adding signed-off commit. 

Signed-off-by: Rajib Mitra <rajib.jolite@gmail.com>

**Comment by rajibmitra** [comment]
closing this for now.

**Pull request closed without merging**
