### PR TITLE
LICENSE

### LINKED ISSUE #20: Missing license
**What would you like to be added**:

The LICENSE file.

**Why is this needed**:

Do I really need to explain why? LOL

### PR DESCRIPTION
**Pull request by leodido**
Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>

**What type of PR is this?**

/kind documentation

/kind feature

**Any specific area of the project related to this PR?**

ALL

**What this PR does / why we need it**:

Adds a LICENSE file.

**Which issue(s) this PR fixes**:

Fixes #20

**Special notes for your reviewer**:

Nope.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by markjacksonfishing — APPROVED** [review]
/lgtm

**Review by markjacksonfishing — APPROVED** [review]
/lgtm

**Review by fntlnz — APPROVED** [review]

**Pull request merged**
